# Generated by scripts/homebrew-formula.sh — do not edit by hand.
class Indice < Formula
  desc "Web archive server: WACZ indexing, full-text search, and replay"
  homepage "https://github.com/edsu/indice"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/edsu/indice/releases/download/v0.2.0/indice-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "6c22d619cbaef9b54a7c2e4552f6b3341efda8b15c18bb72ef62ffe4eb22cd6b"
    end
    on_intel do
      url "https://github.com/edsu/indice/releases/download/v0.2.0/indice-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "fd5e5b485317bf7d4681d00232bae03e657afb0055956f480f53b4fd97e58752"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/edsu/indice/releases/download/v0.2.0/indice-v0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1744db0a626acb1ca997bfd19130d5c59688cb43d72b49f9563cdcd5a5721829"
    end
    on_intel do
      url "https://github.com/edsu/indice/releases/download/v0.2.0/indice-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "987d7e25e5cf83dd2c72e1ecbc32d9b09097d96d89ff49868f24bbcc5c6437e0"
    end
  end

  def install
    bin.install "indice"
  end

  test do
    assert_match "indice", shell_output("#{bin}/indice --help")
  end
end
