# Generated by scripts/homebrew-formula.sh — do not edit by hand.
class Indice < Formula
  desc "Web archive server: WACZ indexing, full-text search, and replay"
  homepage "https://github.com/edsu/indice"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/edsu/indice/releases/download/v0.1.0/indice-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "5525a2e5d96dd9951350a5446e7fc16fd7393f800baec94bf281b5286d270917"
    end
    on_intel do
      url "https://github.com/edsu/indice/releases/download/v0.1.0/indice-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "aa1f87a2acbd4127a8fa9a253e2d76c567c022f865f76ceef1f4ac3e7ff2c7ac"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/edsu/indice/releases/download/v0.1.0/indice-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "06e6ac2ee9ed09604f08a411d0e03f142652acece9a665b73c151f10756f199d"
    end
    on_intel do
      url "https://github.com/edsu/indice/releases/download/v0.1.0/indice-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "bf7bbefbd1298d44f4cfe5fd6e83f8347d109f05510386e760588f94be229aa3"
    end
  end

  def install
    bin.install "indice"
  end

  test do
    assert_match "indice", shell_output("#{bin}/indice --help")
  end
end
